### ISSUE TITLE
Docker Hub Image not reubuilt to utilize latest changes

### ISSUE THREAD

**Issue by swissbuechi** [SoftInstigate/graalvm-maven-docker#4]
I noticed that the latest changes from this repository (updated Maven and GraalVM Versions) did not trigger a rebuild of the Docker Hub Image (https://hub.docker.com/r/softinstigate/graalvm-maven).

Could you maybe create some kind of trigger in Docker Hub to automate the rebuild of the image?
I could alse create a pull request with a github action to trigger the rebuild of the image. (see https://github.com/SoftInstigate/graalvm-maven-docker/pull/5)

Thanks in advance.

**Comment by mkjsix** [comment]
Hi @swissbuechi 
Thank you for your PR, indeed it was a pending task for so long to automate the build with actions...
To be more in control of the image's content and avoid confusion on the meaning of the `latest` tag, I added the constraint that an image is built only when a tag is pushed and the tag must be the same as the Graalvm image version.
