### ISSUE TITLE
Support for the latest JDK22

### ISSUE THREAD

**Issue by KafkaProServerless** [SoftInstigate/graalvm-maven-docker#8]
Hello team,

This is a great image I am using every day.
Thank you so much for the work.

Would it be possible to support the latest JDK22 which is now released?

Thank you

**Comment by ujibang** [comment]
Hi @KafkaProServerless 

we just updated GraalVM to v21.0.2-graalce. We stick at java v21 for now since it is a LTS release.

However if you need GraalVM v22 just fork this repo and set in the Dockerfile

```
ARG JAVA_VERSION="22-graalce"
```

**Comment by KafkaProServerless** [comment]
Will this model of "follow the LTS" works as Java transitions to the 6 months release cadence?

**Comment by mkjsix** [comment]
Image 22.0.2-graalce is now available.

`docker pull softinstigate/graalvm-maven:22.0.2-graalce`
